# This file is to test table generation ignore this file it's not useful
# Mostly for auditing purposes.
from thistle.p384 import U384, P384Point, _scalar_mult, _to_mont


def main() raises:
    # T[j][d] = d * 16^(2j) * G, Montgomery-form affine, j in 0..47, d in 1..15
    # flat layout: ((j * 15) + (d - 1)) * 12 + limb; x limbs 0..5, y limbs 6..11
    var values = List[UInt64](capacity=8704)
    for j in range(48):
        for d in range(1, 16):
            var k = U384()
            k.limbs[(8 * j) // 64] = UInt64(d) << UInt64((8 * j) % 64)
            var pt = _scalar_mult(k, P384Point.generator())
            var mx = _to_mont(pt.x)
            var my = _to_mont(pt.y)
            for l in range(6):
                values.append(mx.limbs[l])
            for l in range(6):
                values.append(my.limbs[l])
    while len(values) < 8704:
        values.append(0)

    print("# generated by tests/gen_p384_table.mojo, do not edit")
    print("from std.builtin.dtype import DType")
    print("from std.builtin.simd import SIMD")
    print("from std.collections import InlineArray")
    print("")
    for c in range(68):
        print("comptime _P384_BT" + String(c) + " = SIMD[DType.uint64, 128](")
        for row in range(16):
            var line = String("    ")
            for col in range(8):
                line += String(values[c * 128 + row * 8 + col]) + ", "
            print(line)
        print(")")
        print("")
    print("def p384_base_table() -> InlineArray[UInt64, 8704]:")
    print("    var t = InlineArray[UInt64, 8704](uninitialized=True)")
    print("    var p = t.unsafe_ptr()")
    for c in range(68):
        print("    p.unsafe_store[alignment=8](" + String(c * 128) + ", _P384_BT" + String(c) + ")")
    print("    return t^")
