# Generate the radix-16 P-256 comb table; this does not generate the W7 table.
from thistle.p256 import U256, P256Point, _scalar_mult, _to_mont


def main() raises:
    # T[j][d] = d * 16^(2*j) * G in Montgomery affine form; j = 0..31, d = 1..15.
    # Entry offset: (j * 15 + d - 1) * 8; x occupies limbs 0..3, y occupies limbs 4..7.
    var values = List[UInt64](capacity=4096)
    for j in range(32):
        for d in range(1, 16):
            var k = U256()
            k.limbs[(8 * j) // 64] = UInt64(d) << UInt64((8 * j) % 64)
            var pt = _scalar_mult(k, P256Point.generator())
            var mx = _to_mont(pt.x)
            var my = _to_mont(pt.y)
            for l in range(4):
                values.append(mx.limbs[l])
            for l in range(4):
                values.append(my.limbs[l])
    while len(values) < 4096:
        values.append(0)

    print("# generated by tests/gen_p256_table.mojo, do not edit")
    print("from std.builtin.dtype import DType")
    print("from std.builtin.simd import SIMD")
    print("from std.collections import InlineArray")
    print("")
    for c in range(32):
        print("comptime _P256_BT" + String(c) + " = SIMD[DType.uint64, 128](")
        for row in range(16):
            var line = String("    ")
            for col in range(8):
                line += String(values[c * 128 + row * 8 + col]) + ", "
            print(line)
        print(")")
        print("")
    print("def p256_base_table() -> InlineArray[UInt64, 4096]:")
    print("    var t = InlineArray[UInt64, 4096](fill=0)")
    print("    var p = t.unsafe_ptr()")
    for c in range(32):
        print("    p.unsafe_store[alignment=8](" + String(c * 128) + ", _P256_BT" + String(c) + ")")
    print("    return t^")
